version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-docker
    build:
      context: ./docker
    ports:
      - "8080:8080"
    volumes:
      - /Users/stephenlane/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
  net:
